// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJPBS_S5Z-K7i7ap1zP3Z64EhDM8T4Ls',
    appId: '1:1060966316344:web:38801588148b01d9a3e9cd',
    messagingSenderId: '1060966316344',
    projectId: 'avocado-d56a7',
    authDomain: 'avocado-d56a7.firebaseapp.com',
    storageBucket: 'avocado-d56a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnJllg2Ke_6D5ToDLg3gUcAroo7S4lTHM',
    appId: '1:1060966316344:android:53e948812ca91e62a3e9cd',
    messagingSenderId: '1060966316344',
    projectId: 'avocado-d56a7',
    storageBucket: 'avocado-d56a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnO9udl6KcWr1nL9SvWpcuzh6M-IbhLYg',
    appId: '1:1060966316344:ios:88931604fe17aaa8a3e9cd',
    messagingSenderId: '1060966316344',
    projectId: 'avocado-d56a7',
    storageBucket: 'avocado-d56a7.appspot.com',
    iosClientId: '1060966316344-1i74qujf7buqbmsfptbvrclmggai2a8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnO9udl6KcWr1nL9SvWpcuzh6M-IbhLYg',
    appId: '1:1060966316344:ios:88931604fe17aaa8a3e9cd',
    messagingSenderId: '1060966316344',
    projectId: 'avocado-d56a7',
    storageBucket: 'avocado-d56a7.appspot.com',
    iosClientId: '1060966316344-1i74qujf7buqbmsfptbvrclmggai2a8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );
}
